"""Session report generator — markdown from session history + loot vault."""
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from config.settings import EXPORTS_DIR
from core.theme import help_footer, status_bar

console = Console()


def _build_report(history, vault, title: str = "Pentest Session Report") -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# {title}",
        f"> Generated: {now}",
        "",
    ]

    # Session commands
    entries = history.last(200) if history else []
    lines += [
        "## Commands Executed",
        "",
        f"Total: {len(entries)}",
        "",
        "| Time | Command | Status |",
        "|------|---------|--------|",
    ]
    for e in entries:
        status = "✓" if e.get("exit_code") == 0 else ("DRY" if e.get("dry_run") else "✗")
        cmd = e.get("command", "")[:80].replace("|", "\\|")
        lines.append(f"| {e.get('timestamp','')} | `{cmd}` | {status} |")
    lines.append("")

    # Loot
    loot_entries = vault.all() if vault else []
    lines += [
        "## Loot Captured",
        "",
        f"Total: {len(loot_entries)}",
        "",
    ]
    by_type: dict = {}
    for e in loot_entries:
        by_type.setdefault(e["type"], []).append(e)
    for t, items in sorted(by_type.items()):
        lines.append(f"### {t.upper()}")
        for item in items:
            lines.append(f"- **[{item['id']}]** `{item['value']}`")
            if item.get("source"):
                lines.append(f"  - Source: {item['source']}")
            if item.get("notes"):
                lines.append(f"  - Notes: {item['notes']}")
            lines.append(f"  - {item.get('timestamp','')}")
        lines.append("")

    lines += [
        "---",
        f"*Report generated by autohack — {now}*",
    ]
    return "\n".join(lines)


class ReportMenu:
    """Générateur de rapports de session."""

    def __init__(self, history=None, vault=None) -> None:
        self._history = history
        self._vault   = vault

    def show(self) -> None:
        while True:
            console.clear()
            console.print(Panel(
                "[bold cyan]Report Generator[/bold cyan]  [dim]— génère un rapport markdown de session[/dim]",
                border_style="cyan", padding=(0, 1),
            ))
            console.print()

            hist_count = len(self._history) if self._history else 0
            loot_count = len(self._vault)   if self._vault   else 0
            status_bar([
                ("Commandes", str(hist_count), "bold bright_cyan"),
                ("Loot",      str(loot_count), "bold bright_yellow"),
                ("Export",    str(EXPORTS_DIR), "grey70"),
            ])
            console.print()

            help_footer([
                ("g",                    "générer et sauvegarder le rapport"),
                ("g <titre>",            "générer avec un titre personnalisé"),
                ("p",                    "prévisualiser dans le terminal"),
                ("b / q",                "retour"),
            ], title="Report Generator")

            try:
                raw = console.input("\n  [bold cyan]>[/bold cyan] ").strip()
            except (KeyboardInterrupt, EOFError):
                break

            if not raw or raw in {"b", "q"}:
                break

            parts = raw.split(None, 1)
            cmd = parts[0].lower()

            if cmd == "p":
                report = _build_report(self._history, self._vault)
                console.print()
                # Print first 60 lines
                for line in report.split("\n")[:60]:
                    console.print(f"  {line}")
                if report.count("\n") > 60:
                    console.print("  [dim]… (rapport tronqué pour l'affichage)[/dim]")
                console.input("\n[dim]  Entrée…[/dim]")

            elif cmd == "g":
                title = parts[1].strip() if len(parts) > 1 else "Pentest Session Report"
                report = _build_report(self._history, self._vault, title)
                EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
                ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
                slug = title.lower().replace(" ", "_")[:30]
                path = EXPORTS_DIR / f"report_{slug}_{ts}.md"
                path.write_text(report, encoding="utf-8")
                console.print(f"\n  [bold green]✓[/bold green] Rapport sauvegardé : [bold white]{path}[/bold white]")
                console.print(f"  [dim]{len(report.splitlines())} lignes · {len(report):,} caractères[/dim]")
                console.input("\n[dim]  Entrée…[/dim]")

            else:
                console.print("  [dim]Commande inconnue. Utilisez g, p, b.[/dim]")
                console.input("[dim]  Entrée…[/dim]")
